### ISSUE TITLE
eksctl releasing is random, still 

### ISSUE THREAD

**Issue by matti** [elementalvoid/asdf-eksctl#4]
https://github.com/weaveworks/eksctl/issues/4858

I made a quick hack like this:

https://github.com/matti/asdf-eksctl/blob/master/bin/install#L39-L48

**Comment by elementalvoid** [comment]
Hey, thanks for the notice @matti. I'll take a look at this today!

**Comment by elementalvoid** [comment]
@matti I used your changes as a base with a couple minor tweaks. Testing locally and via GH Actions all looks good so it's released! Let me know if you see any further issues. And, thanks again for pinging about the issue!
